# Generated by Django 3.0.7 on 2020-06-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_questions_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=250)),
                ('correct_orincorrect', models.CharField(max_length=100)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Questions')),
                ('quiztakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.QuizTakers')),
            ],
        ),
    ]
