# Generated by Django 3.0.7 on 2020-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_usertracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztakers',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
