# Generated by Django 3.0.7 on 2020-06-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20200616_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertracker',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.Questions'),
        ),
    ]
