# Generated by Django 3.0.7 on 2020-06-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20200618_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
                ('questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.Questions')),
                ('quiztakers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.QuizTakers')),
            ],
            options={
                'unique_together': {('username', 'key')},
            },
        ),
    ]
