# Generated by Django 3.0.7 on 2020-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_account_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertracker',
            name='questions',
        ),
        migrations.AddField(
            model_name='usertracker',
            name='questions',
            field=models.ManyToManyField(to='quizapp.Questions'),
        ),
        migrations.RemoveField(
            model_name='usertracker',
            name='quiztakers',
        ),
        migrations.AddField(
            model_name='usertracker',
            name='quiztakers',
            field=models.ManyToManyField(to='quizapp.QuizTakers'),
        ),
    ]
