# Generated by Django 3.0.7 on 2020-06-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20200619_1522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account_data',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='account_data',
            name='username',
        ),
    ]
