# Generated by Django 3.0.7 on 2020-06-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_auto_20200619_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='questions',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quizapp.Questions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_data',
            name='quiztakers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizapp.QuizTakers'),
            preserve_default=False,
        ),
    ]
