# Generated by Django 3.0.7 on 2020-07-01 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0011_auto_20200619_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_data',
            new_name='AccountData',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='QuizTakers',
            new_name='QuizTaker',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-category',)},
        ),
        migrations.RenameField(
            model_name='accountdata',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='accountdata',
            old_name='quiztakers',
            new_name='quiztaker',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='usertracker',
            old_name='correct_orincorrect',
            new_name='correct_or_incorrect',
        ),
        migrations.RemoveField(
            model_name='usertracker',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='usertracker',
            name='quiztakers',
        ),
        migrations.AddField(
            model_name='usertracker',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quizapp.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertracker',
            name='result',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertracker',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
